spring.application.name=microservice-authentification
spring.datasource.url=jdbc:mysql://localhost:3306/authenticationDatabase?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=9050
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9050/oauth2/jwks